spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: oocjAqIPLcmmIiCosJbQzwVnZkCSnqCj
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

app:
  allowed:
    origins: "https://skooly.vercel.app,https://skooly-diwakar-singhs-projects.vercel.app"