package com.skooly.backend.entity;
public enum ElectiveSubject {
   MUSIC,
   PAINTING,
   HOME_SCIENCE,
   NATIONAL_CADET_CORPS,
   COMPUTER_APPLICATIONS,
   BIO_TECHNOLOGY,
   COMPUTER_SCIENCE_XI,
   COMPUTER_SCIENCE_XII,
   DANCE,
   ENGINEERING_GRAPHICS,
   ENTREPRENEURSHIP,
   ART,
   GEOGRAPHY,
   HISTORY,
   INFO_PRACTICES_XI,
   INFO_PRACTICES_XII,
   LEGAL_STUDIES,
   PHYSICAL_EDUCATION,
   POLITICAL_SCIENCE,
   PSYCHOLOGY,
   SOCIOLOGY
}